Lab Session/Lab Programs/25-08-2022 Program/Models/ErrorViewModel.cs
namespace WebCalculator.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab Session/Lab Programs/25-08-2022 Program/Models/WebCalc.cs
namespace WebCalculator.Models
{
    public class WebCalc
    {
        public int FirstNumber { get; set; }
        public int SecondNumber { get; set; }
        public int Result { get; set; }
        public string calc { get; set; }
    }
}

Lab Session/Lab Programs/25-08-2022 Program/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebCalculator.Models;

namespace WebCalculator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab Session/Lab Programs/25-08-2022 Program/Controllers/WCController.cs
using Microsoft.AspNetCore.Mvc;
using WebCalculator.Models;

namespace WebCalculator.Controllers
{
    public class WCController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(WebCalc wc)
        {
            if(wc.calc == "Addition")
            {
                wc.Result = wc.FirstNumber + wc.SecondNumber;
            }
            else if(wc.calc == "Subtraction")
            {
                wc.Result = wc.FirstNumber - wc.SecondNumber;
            }
            else if (wc.calc == "Multiplication")
            {
                wc.Result = wc.FirstNumber * wc.SecondNumber;
            }
            else if (wc.calc == "Division")
            {
                wc.Result = wc.FirstNumber / wc.SecondNumber;
            }
            else
            {
                wc.Result = 666;
            }
            return View(wc);
        }

    }
}

Lab Session/Lab Programs/25-08-2022 Program/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">This Web Calculator is Developed By</h1>
    <h1 class="display-4"> Arun Dotnet Batch</h1>
    <h1 class="display-4"> Anudip</h1>
</div>

Lab Session/Lab Programs/25-08-2022 Program/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCalculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebCalculator.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebCalculator</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WC" asp-action="Index">Calculator</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebCalculator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Lab Session/Lab Programs/25-08-2022 Program/Views/WC/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <body>
        @model WebCalculator.Models.WebCalc
        @using (Html.BeginForm("Index","WC",FormMethod.Post)){

            <div>
            <br />
            <br />
            <h1 style="color :firebrick  ; font-weight : bold">Web Calculator</h1>
            <br />
            <label>Enter a Number :     </label>
            @Html.Editor("FirstNumber")
            <br />
            <br/>
            <label>Enter Another Number : </label>
            @Html.Editor("SecondNumber")
            <br/>
            <br/>
            <div style>
                <input style="color : darkred" type="submit" value="Addition" asp-for="calc"/>
                <input style="color : darkmagenta" type="submit" value="Subtraction" asp-for="calc" />
                <input style="color : deepskyblue" type="submit" value="Multiplication" asp-for="calc" />
                <input style="color : limegreen" type="submit" value="Division" asp-for="calc" />
            </div>
            <br/>
             <h3>Result = @Html.Display("Result")</h3>
           

            </div>
        }
    </body>
</html>